hydra:
  run:
    dir: /export/livia/home/vision/Myazdanpanah/projects/SAM-6D/SAM-6D/Instance_Segmentation_Model
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: .pl_ddp_hydra_1
  overrides:
    hydra:
    - hydra.output_subdir=.pl_ddp_hydra_1
    - hydra.run.dir=/export/livia/home/vision/Myazdanpanah/projects/SAM-6D/SAM-6D/Instance_Segmentation_Model
    - hydra.mode=RUN
    task: []
  job:
    name: run_inference
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: config.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /export/livia/home/vision/Myazdanpanah/projects/SAM-6D/SAM-6D/Instance_Segmentation_Model
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /export/livia/home/vision/Myazdanpanah/projects/SAM-6D/SAM-6D/Instance_Segmentation_Model
      schema: file
      provider: main
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: ''
      schema: structured
      provider: schema
    output_dir: /export/livia/home/vision/Myazdanpanah/projects/SAM-6D/SAM-6D/Instance_Segmentation_Model
    choices:
      model: ISM_fastsam
      model/descriptor_model: dinov2
      model/segmentor_model: fast_sam
      data: bop
      callback: base
      callback/lr: base
      callback/checkpoint: base
      machine: local
      machine/trainer: local
      user: default
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
